eBank/Models/Simulation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace eBank.Models
{
    public class SimulationManager
    {
        public Purchase PurchaseSingleItem(StoreItem item, Student stud, Account acct, Account savings)
        {
            if ((item.EnergyChange >= 0) || CanCompleteAction(stud.Energy, item.EnergyChange))
            {

                var purchase = new Purchase { PurchaseDate = DateTime.Now.Date, StoreItemName = item.StoreItemName, ItemPrice = item.ItemPrice, StoreName = item.Store.StoreName, StudentID = stud.UserId };

                stud.Energy += item.EnergyChange;
                stud.Happiness += item.HappinessChange;
                stud.Health += item.HealthChange;
                stud.Hunger += item.HungerChange;
                stud.Social += item.SocialChange;

                if (stud.Energy > 100) stud.Energy = 100;
                if (stud.Happiness > 100) stud.Happiness = 100;
                if (stud.Health > 100) stud.Health = 100;
                if (stud.Hunger > 100) stud.Hunger = 100;
                if (stud.Social > 100) stud.Social = 100;

                if (stud.Energy < 0) stud.Energy = 0;
                if (stud.Happiness < 0) stud.Happiness = 0;
                if (stud.Health < 0) stud.Health = 0;
                if (stud.Hunger < 0) stud.Hunger = 0;
                if (stud.Social < 0) stud.Social = 0;

                if (acct.AccountTotal < item.ItemPrice)
                {
                    decimal remainder = Math.Abs(acct.AccountTotal - item.ItemPrice);

                    if (savings.AccountTotal >= remainder)
                    {
                        acct.AccountTotal = 0;
                        savings.AccountTotal -= remainder;
                        savings.AccountTotal -= 5; //Overdraft
                        stud.bBillsPaid = false;
                    }
                    else if (savings.AccountTotal < remainder)
                    {
                        savings.AccountTotal -= remainder;
                        savings.AccountTotal -= 28; //Overdraft
                        //stud.bBillsPaid = false;
                    }
                }
                else acct.AccountTotal -= item.ItemPrice;

                return purchase;
            }
            else return null;
        }

        //TODO: Add up the price of all items then do overdrafts at the very end instead of after every item
        public ICollection<Purchase> PurchaseMultipleItems(ICollection<StoreItem> items, Student stud, Account acct, Account savings)
        {

            ICollection<Purchase> purchases = new List<Purchase>();

            foreach (var storeItem in items)
            {
                if ((storeItem.EnergyChange >= 0) || CanCompleteAction(stud.Energy, storeItem.EnergyChange))
                {

                    var purchase = new Purchase { PurchaseDate = DateTime.Now.Date, StoreItemName = storeItem.StoreItemName, ItemPrice = storeItem.ItemPrice, StoreName = storeItem.Store.StoreName, StudentID = stud.UserId };
                    purchases.Add(purchase);

                    stud.Energy += storeItem.EnergyChange;
                    stud.Happiness += storeItem.HappinessChange;
                    stud.Health += storeItem.HealthChange;
                    stud.Hunger += storeItem.HungerChange;
                    stud.Social += storeItem.SocialChange;

                    if (stud.Energy > 100) stud.Energy = 100;
                    if (stud.Happiness > 100) stud.Happiness = 100;
                    if (stud.Health > 100) stud.Health = 100;
                    if (stud.Hunger > 100) stud.Hunger = 100;
                    if (stud.Social > 100) stud.Social = 100;

                    if (stud.Energy < 0) stud.Energy = 0;
                    if (stud.Happiness < 0) stud.Happiness = 0;
                    if (stud.Health < 0) stud.Health = 0;
                    if (stud.Hunger < 0) stud.Hunger = 0;
                    if (stud.Social < 0) stud.Social = 0;

                    if (acct.AccountTotal < storeItem.ItemPrice)
                    {
                        decimal remainder = Math.Abs(acct.AccountTotal - storeItem.ItemPrice);

                        if (savings.AccountTotal >= remainder)
                        {
                            acct.AccountTotal = 0;
                            savings.AccountTotal -= remainder;
                            savings.AccountTotal -= 5;
                            //stud.bBillsPaid = false;
                        }
                        else if (savings.AccountTotal < remainder)
                        {
                            savings.AccountTotal -= remainder;
                            savings.AccountTotal -= 28; //Overdraft
                            //stud.bBillsPaid = false;
                        }
                    }
                    else acct.AccountTotal -= storeItem.ItemPrice;
                }
            }
            return purchases; //Maybe add else return null
        }

        public bool CanCompleteAction(decimal studEnergy, decimal itemEnergy)
        {
            if (((studEnergy) + (itemEnergy)) >= 0)
            {
                return true;
            }
            else return false;
        }
    }
}

eBank/Controllers/SimulationController.cs
using eBank.DAL;
using eBank.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;

namespace eBank.Controllers
{
    public class SimulationController : Controller
    {
        private BankContext db = new BankContext();

        public ActionResult Index()
        {
            return View();
        }
         
        /** Food Methods Start **/

        [HttpGet]
        public ActionResult Food()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult GotoFancy() 
        {
            Store store = db.Stores.Find(1);
            return PartialView(store);
        }

        [HttpGet]
        public PartialViewResult GotoBurger()
        {
            Store store = db.Stores.Find(2);
            return PartialView(store);
        }

        [HttpGet]
        public PartialViewResult GotoRamen()
        {
            Store store = db.Stores.Find(3);
            return PartialView(store);
        }

        public RedirectToRouteResult PurchaseSingleItem(int id)
        {
            SimulationManager mgr = new SimulationManager();

            var item = db.StoreItems.Find(id);

            var userProfile = db.UserProfiles.Local.SingleOrDefault(u => u.UserName == User.Identity.Name)
                ?? db.UserProfiles.SingleOrDefault(u => u.UserName == User.Identity.Name);

            var student = db.Students.Find(userProfile.UserId);

            var accounts = db.Accounts.Where(x => x.StudentID == student.UserId);

            var account = accounts.FirstOrDefault();

            var accountSavings = accounts.Single(x => x.AccountName == "Savings");

            var purchase = mgr.PurchaseSingleItem(item, student, account, accountSavings);

            db.Purchases.Add(purchase);
            db.SaveChanges();

            return RedirectToAction("Index", "Student");
        }

        /** Convience Methods Start **/

        [HttpGet]
        public ActionResult Convenience()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult GotoGas()
        {
            Store store = db.Stores.Find(4);
            return PartialView(store);
        }

        public ActionResult GotoQuickMart()
        {
            return View(db.Stores.Find(6));
        }

        public ActionResult GotoMEGASpeedyStop()
        {
            return View(db.Stores.Find(7));
        }

        [HttpPost]
        public RedirectToRouteResult PurchaseMultipleItems(List<int> MultipleItemsCheckboxes)
        {
            SimulationManager mgr = new SimulationManager();

            ICollection<StoreItem> items = new List<StoreItem>(); //Don't know if this will work

            var userProfile = db.UserProfiles.Local.SingleOrDefault(u => u.UserName == User.Identity.Name)
                ?? db.UserProfiles.SingleOrDefault(u => u.UserName == User.Identity.Name);

            var student = db.Students.Find(userProfile.UserId);

            var studentExpenses = student.StudentExpenses; //Not sure if this is right?

            var accounts = db.Accounts.Where(x => x.StudentID == student.UserId);

            var account = accounts.FirstOrDefault();

            var accountSavings = accounts.Single(x => x.AccountName == "Savings");

            if (MultipleItemsCheckboxes != null)
            {
                foreach (var item in MultipleItemsCheckboxes)
                {
                    var storeItem = db.StoreItems.Find(item);
                    items.Add(storeItem);
                }

                //var purchases = mgr.PurchaseMultipleItems(items, student, account, accountSavings, studentExpenses);

                //foreach (var item in purchases)
                //{
                //    db.Purchases.Add(item);
                //}

                db.SaveChanges();

                return RedirectToAction("Index", "Student");
            }
            else return RedirectToAction("Index"); //Set up error 
        }
        
        /** Health Methods Start **/
        public ActionResult Health()
        {
            return View();
        }


        public ActionResult GotoDrugStore()
        {
            return View(db.Stores.Find(8));
        }

        public ActionResult GotoGym()
        {
            return View(db.Stores.Find(9));
        }

        public ActionResult GotoShakeStore()
        {
            return View(db.Stores.Find(10));
        }

        public ActionResult GotoVivaVitamin()
        {
            return View(db.Stores.Find(11));
        }

        public ActionResult GotoHospital()
        {
            return View(db.Stores.Find(12));
        }

        public ActionResult GotoSportingStop()
        {
            return View(db.Stores.Find(13));
        }


        /** Fun Methods Start **/
        public ActionResult Fun()
        {
            return View();
        }

        public ActionResult GotoSkyDiving()
        {
            return View(db.Stores.Find(5));
        }

        public ActionResult GotoMovieTheater()
        {
            return View(db.Stores.Find(14));
        }

        public ActionResult GotoPark()
        {
            return View(db.Stores.Find(15));
        }

        public ActionResult GotoBowling()
        {
            return View(db.Stores.Find(16));
        }

        public ActionResult GotoAmusementPark()
        {
            return View(db.Stores.Find(17));
        }

        public ActionResult GotoTheLake()
        {
            return View(db.Stores.Find(18));
        }

        /** Daily Events **/
        public ActionResult DailyEvents()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

eBank/Views/Simulation/Convenience.cshtml
@{
    ViewBag.Title = "Food";
    Layout = "~/Views/Shared/_FoodLayout.cshtml";
}

@model eBank.Models.Store

<link rel="stylesheet" type="text/css" href="~/Content/Simulation.css" />

<div class="freshdesignweb">
    <article class="border c-two" style="background-image: url('/Content/images/Gas.jpg')">
        <div style="opacity: 0;" class="fdw-background">
            <h4 style="color:#fff;">Gas</h4>
            <p class="fdw-port">
                @Ajax.ActionLink("Go Now", "GotoGas", "Simulation", new AjaxOptions { UpdateTargetId = "Rest", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" })<span class="vg-icon">→</span>
            </p>
        </div>
    </article>

    <article class="border c-two" style="background-image: url('/Content/images/Mart.jpg')">
        <div style="opacity: 0;" class="fdw-background">
            <h4 style="color:#fff;">Quick Mart</h4>
            <p class="fdw-port">
                @Html.ActionLink("Go Now", "GotoQuickMart", "Simulation")<span class="vg-icon">→</span>
            </p>
        </div>
    </article>

    <article class="border c-two" style="background-image: url('/Content/images/SpeedyStop.jpg')">
        <div style="opacity: 0;" class="fdw-background">
            <h4 style="color:#fff;">MEGA Speedy Stop</h4>
            <p class="fdw-port">
                @Ajax.ActionLink("Go Now", "GotoMEGASpeedyStop", "Simulation", new { id = 3 }, new AjaxOptions { UpdateTargetId = "Rest", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" })<span class="vg-icon">→</span>
            </p>
        </div>
    </article>
</div>

<div id="Rest">

</div>
 

eBank/Views/Simulation/Fun.cshtml
@{
    ViewBag.Title = "Fun";
    Layout = "~/Views/Shared/_FoodLayout.cshtml";
}

@model eBank.Models.Store

<link rel="stylesheet" type="text/css" href="~/Content/Simulation.css" />

<div class="freshdesignweb" width="950" style="margin-left:auto;margin-right:auto">
    <article class="border c-two" style="background-image: url('/Content/images/Theater.jpg')">
        <div style="opacity: 0;" class="fdw-background">
            <h4 style="color:#fff;">Movie Theater</h4>
            <p class="fdw-port">
                @Html.ActionLink("Go Now", "GotoMovieTheater", "Simulation")<span class="vg-icon">→</span>
            </p>
        </div>
    </article>

    <article class="border c-two" style="background-image: url('/Content/images/SkyDive.jpg')">
        <div style="opacity: 0;" class="fdw-background">
            <h4 style="color:#fff;">Super Sky Diving</h4>
            <p class="fdw-port">
                @Html.ActionLink("Go Now", "GotoSkyDiving", "Simulation")<span class="vg-icon">→</span>
            </p>
        </div>
    </article>

    <article class="border c-two" style="background-image: url('/Content/images/Park.jpg')">
        <div style="opacity: 0;" class="fdw-background">
            <h4 style="color:#fff;">Park</h4>
            <p class="fdw-port">
                @Html.ActionLink("Go Now", "GotoPark", "Simulation")<span class="vg-icon">→</span>
            </p>
        </div>
    </article>

    <article class="border c-two" style="background-image: url('/Content/images/Bowling.jpg')">
        <div style="opacity: 0;" class="fdw-background">
            <h4 style="color:#fff;">Bowling Alley</h4>
            <p class="fdw-port">
                @Html.ActionLink("Go Now", "GotoBowling", "Simulation")<span class="vg-icon">→</span>
            </p>
        </div>
    </article>

    <article class="border c-two" style="background-image: url('/Content/images/Amusement.jpg')">
        <div style="opacity: 0;" class="fdw-background">
            <h4 style="color:#fff;">Amusement Park</h4>
            <p class="fdw-port">
                @Html.ActionLink("Go Now", "GotoAmusementPark", "Simulation")<span class="vg-icon">→</span>
            </p>
        </div>
    </article>

    <article class="border c-two" style="background-image: url('/Content/images/Lake.jpg')">
        <div style="opacity: 0;" class="fdw-background">
            <h4 style="color:#fff;">The Lake</h4>
            <p class="fdw-port">
                @Html.ActionLink("Go Now", "GotoTheLake", "Simulation")<span class="vg-icon">→</span>
            </p>
        </div>
    </article>
</div>

<div id="Rest">

</div>

eBank/Views/Simulation/GotoAmusementPark.cshtml
@model eBank.Models.Store

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Content/Simulation.css" />

<fieldset>
    <legend>Amusement Park</legend>

    <div class="StoreName" align="center">
        @Html.DisplayFor(model => model.StoreName)
    </div>

    <table width="200" style="margin-left:auto;margin-right:auto">
        <thead><tr>
            <th align="center">Activity</th>
            <th align="center">Description</th>
            <th align="center">Price</th>
            <th></th>
               </tr></thead>
        <tbody>
            @foreach (var item in Model.StoreItems)
            {
                <tr>
                    <td>@Html.DisplayFor(i => item.StoreItemName)</td>
                    <td>@Html.DisplayFor(i => item.ItemDescription)</td>
                    <td>@Html.DisplayFor(i => item.ItemPrice)</td>
                    <td>
                        @using(Html.BeginForm("PurchaseSingleItem", "Simulation", new { id = item.StoreItemID })) {
                            <input class="PurchaseButton" type="submit" value="GO!" />
                        }
                    </td>
                </tr> 
            }
        </tbody>
    </table>
</fieldset>

eBank/Views/Simulation/GotoBowling.cshtml
@model eBank.Models.Store

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Content/Simulation.css" />

<fieldset>
    <legend>Bowling</legend>

    <div class="StoreName" align="center">
        @Html.DisplayFor(model => model.StoreName)
    </div>

    <table width="200" style="margin-left:auto;margin-right:auto">
        <thead><tr>
            <th align="center">Option</th>
            <th align="center">Description</th>
            <th align="center">Price</th>
            <th></th>
               </tr></thead>
        <tbody>
            @foreach (var item in Model.StoreItems)
            {
                <tr>
                    <td>@Html.DisplayFor(i => item.StoreItemName)</td>
                    <td>@Html.DisplayFor(i => item.ItemDescription)</td>
                    <td>@Html.DisplayFor(i => item.ItemPrice)</td>
                    <td>
                        @using(Html.BeginForm("PurchaseSingleItem", "Simulation", new { id = item.StoreItemID })) {
                            <input class="PurchaseButton" type="submit" value="Bowl!" />
                        }
                    </td>
                </tr> 
            }
        </tbody>
    </table>
</fieldset>

eBank/Views/Simulation/GotoBurger.cshtml
@model eBank.Models.Store

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Content/Simulation.css" />

<fieldset>
    <legend>Fancy</legend>

    <div class="StoreName" align="center">
        @Html.DisplayFor(model => model.StoreName)
    </div>

    <h2 align="center">Menu</h2>
    <table width="200" style="margin-left:auto;margin-right:auto">
        <thead><tr>
            <th align="center">Dish</th>
            <th align="center">Description</th>
            <th align="center">Price</th>
            <th></th>
               </tr></thead>
        <tbody>
            @foreach (var item in Model.StoreItems)
            {
                <tr>
                    <td>@Html.DisplayFor(i => item.StoreItemName)</td>
                    <td>@Html.DisplayFor(i => item.ItemDescription)</td>
                    <td>@Html.DisplayFor(i => item.ItemPrice)</td>
                    <td>
                        @using(Html.BeginForm("PurchaseSingleItem", "Simulation", new { id = item.StoreItemID })) {
                            <input class="PurchaseButton" type="submit" value="Order" />
                        }
                    </td>
                </tr> 
            }
        </tbody>
    </table>
</fieldset>

eBank/Views/Simulation/GotoGas.cshtml
@model eBank.Models.Store

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Content/Simulation.css" />

<fieldset>
    <legend>Gas Station</legend>

    <div class="StoreName" align="center">
        @Html.DisplayFor(model => model.StoreName)
    </div>

    @using(Html.BeginForm("PurchaseMultipleItems", "Simulation")) {
    <table width="200" style="margin-left:auto;margin-right:auto">
        <thead><tr>
            <th align="center">Dish</th>
            <th align="center">Description</th>
            <th align="center">Price</th>
            <th align="left">Cart</th>
               </tr></thead>
        <tbody>
            @foreach (var item in Model.StoreItems)
            {
                <tr>
                    <td>@Html.DisplayFor(i => item.StoreItemName)</td>
                    <td>@Html.DisplayFor(i => item.ItemDescription)</td>
                    <td>@Html.DisplayFor(i => item.ItemPrice)</td>
                    <td>
                        <input type="checkbox" name="MultipleItemsCheckboxes" class="GasCheckboxes" value="@item.StoreItemID" />
                    </td>
                </tr> 
            }
        </tbody>
    </table>
    <div class="SubmitCart" align="center">
        <input type="submit" value="Checkout" />
    </div>
    }
</fieldset>

eBank/Views/Simulation/GotoGym.cshtml
@model eBank.Models.Store

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Content/Simulation.css" />

<fieldset>
    <legend>Gym</legend>

    <div class="StoreName" align="center">
        @Html.DisplayFor(model => model.StoreName)
    </div>

    <table width="200" style="margin-left:auto;margin-right:auto">
        <thead><tr>
            <th align="center">Activity</th>
            <th align="center">Description</th>
            <th align="center">Price</th>
            <th></th>
               </tr></thead>
        <tbody>
            @foreach (var item in Model.StoreItems)
            {
                <tr>
                    <td>@Html.DisplayFor(i => item.StoreItemName)</td>
                    <td>@Html.DisplayFor(i => item.ItemDescription)</td>
                    <td>@Html.DisplayFor(i => item.ItemPrice)</td>
                    <td>
                        @using(Html.BeginForm("PurchaseSingleItem", "Simulation", new { id = item.StoreItemID })) {
                            <input class="PurchaseButton" type="submit" value="GO!" />
                        }
                    </td>
                </tr> 
            }
        </tbody>
    </table>
</fieldset>

eBank/Views/Simulation/GotoHospital.cshtml
@model eBank.Models.Store

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Content/Simulation.css" />

<fieldset>
    <legend>Hospital</legend>

    <div class="StoreName" align="center">
        @Html.DisplayFor(model => model.StoreName)
    </div>

    <table width="200" style="margin-left:auto;margin-right:auto">
        <thead><tr>
            <th align="center">Operation</th>
            <th align="center">Description</th>
            <th align="center">Price</th>
            <th></th>
               </tr></thead>
        <tbody>
            @foreach (var item in Model.StoreItems)
            {
                <tr>
                    <td>@Html.DisplayFor(i => item.StoreItemName)</td>
                    <td>@Html.DisplayFor(i => item.ItemDescription)</td>
                    <td>@Html.DisplayFor(i => item.ItemPrice)</td>
                    <td>
                        @using(Html.BeginForm("PurchaseSingleItem", "Simulation", new { id = item.StoreItemID })) {
                            <input class="PurchaseButton" type="submit" value="Begin Operation" />
                        }
                    </td>
                </tr> 
            }
        </tbody>
    </table>
</fieldset>

eBank/Views/Simulation/GotoMovieTheater.cshtml
@model eBank.Models.Store

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Content/Simulation.css" />

<fieldset>
    <legend>Movie Theater</legend>

    <div class="StoreName" align="center">
        @Html.DisplayFor(model => model.StoreName)
    </div>

    @using(Html.BeginForm("PurchaseMultipleItems", "Simulation")) {
    <table width="200" style="margin-left:auto;margin-right:auto">
        <thead><tr>
            <th align="center">Dish</th>
            <th align="center">Description</th>
            <th align="center">Price</th>
            <th align="left">Cart</th>
               </tr></thead>
        <tbody>
            @foreach (var item in Model.StoreItems)
            {
                <tr>
                    <td>@Html.DisplayFor(i => item.StoreItemName)</td>
                    <td>@Html.DisplayFor(i => item.ItemDescription)</td>
                    <td>@Html.DisplayFor(i => item.ItemPrice)</td>
                    <td>
                        <input type="checkbox" name="MultipleItemsCheckboxes" class="GasCheckboxes" value="@item.StoreItemID" />
                    </td>
                </tr> 
            }
        </tbody>
    </table>
    <div class="SubmitCart" align="center">
        <input type="submit" value="Watch Movie" />
    </div>
    }
</fieldset>

eBank/Views/Simulation/GotoQuickMart.cshtml
@model eBank.Models.Store

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Content/Simulation.css" />

<fieldset>
    <legend>Quick Mart</legend>

    <div class="StoreName" align="center">
        @Html.DisplayFor(model => model.StoreName)
    </div>

    @using(Html.BeginForm("PurchaseMultipleItems", "Simulation")) {
    <table width="200" style="margin-left:auto;margin-right:auto">
        <thead><tr>
            <th align="center">Items</th>
            <th align="center">Description</th>
            <th align="center">Price</th>
            <th align="left">Cart</th>
               </tr></thead>
        <tbody>
            @foreach (var item in Model.StoreItems)
            {
                <tr>
                    <td>@Html.DisplayFor(i => item.StoreItemName)</td>
                    <td>@Html.DisplayFor(i => item.ItemDescription)</td>
                    <td>@Html.DisplayFor(i => item.ItemPrice)</td>
                    <td>
                        <input type="checkbox" name="MultipleItemsCheckboxes" class="GasCheckboxes" value="@item.StoreItemID" />
                    </td>
                </tr> 
            }
        </tbody>
    </table>
    <div class="SubmitCart" align="center">
        <input type="submit" value="Checkout" />
    </div>
    }
</fieldset>

eBank/Views/Simulation/GotoRamen.cshtml
@model eBank.Models.Store

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Content/Simulation.css" />

<fieldset>
    <legend>Fancy</legend>

    <div class="StoreName" align="center">
        @Html.DisplayFor(model => model.StoreName)
    </div>

    <h2 align="center">Menu</h2>
    <table width="200" style="margin-left:auto;margin-right:auto">
        <thead><tr>
            <th align="center">Dish</th>
            <th align="center">Description</th>
            <th align="center">Price</th>
            <th></th>
               </tr></thead>
        <tbody>
            @foreach (var item in Model.StoreItems)
            {
                <tr>
                    <td>@Html.DisplayFor(i => item.StoreItemName)</td>
                    <td>@Html.DisplayFor(i => item.ItemDescription)</td>
                    <td>@Html.DisplayFor(i => item.ItemPrice)</td>
                    <td>
                        @using(Html.BeginForm("PurchaseSingleItem", "Simulation", new { id = item.StoreItemID })) {
                            <input class="PurchaseButton" type="submit" value="Order" />
                        }
                    </td>
                </tr> 
            }
        </tbody>
    </table>
</fieldset>

eBank/Views/Simulation/GotoSportingStop.cshtml
@model eBank.Models.Store

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Content/Simulation.css" />

<fieldset>
    <legend>Sporting Stop</legend>

    <div class="StoreName" align="center">
        @Html.DisplayFor(model => model.StoreName)
    </div>

    @using(Html.BeginForm("PurchaseMultipleItems", "Simulation")) {
    <table width="200" style="margin-left:auto;margin-right:auto">
        <thead><tr>
            <th align="center">Items</th>
            <th align="center">Description</th>
            <th align="center">Price</th>
            <th align="left">Cart</th>
               </tr></thead>
        <tbody>
            @foreach (var item in Model.StoreItems)
            {
                <tr>
                    <td>@Html.DisplayFor(i => item.StoreItemName)</td>
                    <td>@Html.DisplayFor(i => item.ItemDescription)</td>
                    <td>@Html.DisplayFor(i => item.ItemPrice)</td>
                    <td>
                        <input type="checkbox" name="MultipleItemsCheckboxes" class="GasCheckboxes" value="@item.StoreItemID" />
                    </td>
                </tr> 
            }
        </tbody>
    </table>
    <div class="SubmitCart" align="center">
        <input type="submit" value="Checkout" />
    </div>
    }
</fieldset>

eBank/Views/Simulation/GotoVivaVitamin.cshtml
@model eBank.Models.Store

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Content/Simulation.css" />

<fieldset>
    <legend>Viva Vitamin</legend>

    <div class="StoreName" align="center">
        @Html.DisplayFor(model => model.StoreName)
    </div>

    @using(Html.BeginForm("PurchaseMultipleItems", "Simulation")) {
    <table width="200" style="margin-left:auto;margin-right:auto">
        <thead><tr>
            <th align="center">Items</th>
            <th align="center">Description</th>
            <th align="center">Price</th>
            <th align="left">Cart</th>
               </tr></thead>
        <tbody>
            @foreach (var item in Model.StoreItems)
            {
                <tr>
                    <td>@Html.DisplayFor(i => item.StoreItemName)</td>
                    <td>@Html.DisplayFor(i => item.ItemDescription)</td>
                    <td>@Html.DisplayFor(i => item.ItemPrice)</td>
                    <td>
                        <input type="checkbox" name="MultipleItemsCheckboxes" class="GasCheckboxes" value="@item.StoreItemID" />
                    </td>
                </tr> 
            }
        </tbody>
    </table>
    <div class="SubmitCart" align="center">
        <input type="submit" value="Checkout" />
    </div>
    }
</fieldset>